### ISSUE TITLE
Document different Raw Temperature Data behavior depending on mode

### ISSUE THREAD

**Issue by simonft** [combustion-inc/combustion-documentation#21]
I'm actually not sure if this is a documentation issue or a firmware bug. When the probe is in instant read mode, reading [Raw Temperature Data](https://github.com/combustion-inc/combustion-documentation/blob/main/probe_ble_specification.rst#id54) from the [Probe Status Service](https://github.com/combustion-inc/combustion-documentation/blob/main/probe_ble_specification.rst#id21) will only return a real temperature for thermistor 1. The rest of them return 0. When it switches to normal mode all the thermistors return correct temperatures.

I guess this makes some sense, but it wasn't expected to me because the app shows values for all eight sensors in both modes. I have yet to get notify/subscriptions working, and I haven't tested reading this data from the display or other services on the probe, so it's possible those work as I initially expected.

It's not a big deal, especially if there's another place to read those values in both modes, but it did trip me up when trying to parse the data so it may be worth noting in the docs. I'm new to messing with data over bluetooth, so it's possible I've done something wrong here. And if you want a repro example I have some messy rust code or I could probably get a cleaner python version of it.

**Comment by jmaha** [comment]
Hi @simonft, this is expected behavior. When the probe is in Instant Read mode you'll get a combination of Instant Read and Normal Mode status notifications and advertisements. Instant Read messages only contain a single temperature reading in the T1 position, as this is the only sensor that's run through the Instant Read filter algorithm. The Normal Mode messages will contain the raw readings of all 8 sensors. Those Normal Mode status notifications will arrive every 5 seconds.

**Comment by jmaha** [comment]
Also, good catch, thanks--this is a gap in the documentation. We'll add some clarification explaining how Instant Read mode works.

**Comment by simonft** [comment]
Ah, that makes sense, thanks for the explanation. I'm guessing if I'm reading from the Probe Status instead of subscribing I'll get whichever of instant read or normal mode advertisements was sent out last? That would explain why  a few times  I got  data for all five sensors when in instant read mode. If I'm doing the math right the chance of that happening is less than 1 in 50.

**Comment by jmaha** [comment]
Oh yeah, you definitely want to subscribe to that Probe Status characteristic. Instant Read notifications go out 4x / second, so they’re constantly overwriting what’s in that characteristic.

**Comment by jmaha** [comment]
I added a clarifying note to the documentation explaining that Instant Read messages will have the temperature in position 1, with the other 7 blank.
