### ISSUE TITLE
Confirm food-safe data specification

### ISSUE THREAD

**Issue by legrego** [combustion-inc/combustion-documentation#24]
I'm having a hard time parsing the food safe data from my probe, using the specification in the docs. I'm inclined to believe the docs are correct, given my lack of experience working with binary data, but I'd love for someone to help me understand what I'm looking at.

Given the following notification from the Probe Status Service:

```
00000000 00000000 00000000 00000000 01100011 00000001 00000000 00000000
00100100 10000011 01100100 10010000 10001100 10010001 10100001 00110010
01001100 11000110 11001001 00111000 00011001 00000000 11000000 00010000
00100000 00000010 11110000 11111111 01011111 00110010 00100001 00100000 
11101000 10000100 00001101 11000000 00010010 11111001 01101000 00000100
00000000 00000000 00000000 00000000
```

I extract the 10-bytes of Food Safe Data:
```
00100001 00100000 11101000 10000100 00001101 11000000 00010010 11111001 01101000 00000100
```

The docs state that bits 1-3 should be the `Food Safe Mode`, but my testing is showing that these bits are a part of the `Product`.

Here is a collection of different `Food Safe Data` responses. All were configured using the `Integrated` Food Safe Mode and `Serve Immediately` Serving value. The Product value is what I changed from response-to-response, as indicated in the comment next to each byte sequence:

```
00001001 00000000 01000000 10000100 00001110 11000000 00010010 01010100 00010100 00000100 # FSD Beef (0x01)
00010001 00000000 11101000 10000100 00001110 11000000 00010010 01010100 00010100 00000100 # FSD Ground Beef (0x02)
00011001 00000000 10000100 10000100 00001101 11000000 00010010 11111001 01101000 00000100 # FSD Chicken (0x03)
00100001 00000000 11101000 10000100 00001101 11000000 00010010 11111001 01101000 00000100 # FSD Ground Chicken (0x04)
```

Here, we can see bits 3-5 counting up from 1 -> 4, which represents the 4 different products I tested.

I'm also seeing the `Serving` bits represented in locations 9-11 (the first 3 bits of the second byte), instead of the documented 14-16. I determined this by inspecting the sequences between the `FSD Ground Chicken` example above, and another sample I took which changed the Serving to `Cooked and Chilled` (0x01):

```
00100001 00000000 11101000 10000100 00001101 11000000 00010010 11111001 01101000 00000100 # FSD Ground Chicken, serve immediately
00100001 00100000 11101000 10000100 00001101 11000000 00010010 11111001 01101000 00000100 # FSD Ground Chicken, cook and chill
```

So, given the discrepancies I've found so far:
1) What am I doing wrong? Am I looking at the wrong byte sequence, or looking at the sequence incorrectly?
2) Is there a chance that the documentation is incorrect, or am I mis-interpreting the documentation?

Thanks for your time, and for your fantastic work on the documentation and code samples

**Comment by jmaha** [comment]
Thanks for reaching out. This is definitely a confusing aspect of packed C/C++ structs with bit-fields on our ARM devices. At some point I hope to clean up and release our Python-based libraries for interfacing with probes and repeater devices, which would provide helpful example code for decoding these fields.

When we store these data structures in our C++ code, they get byte-swapped and then stored in reverse order. If you're decoding this data in C/C++, you simply overlay the appropriate struct on the data as defined in the documentation and it's decoded automatically. If you're using Python or some other language, you have to jump through some hoops to decode it properly.

Here's a code snippet illustrating how to decode such data using `python` and the `bitstruct` package. *Note that this is decoding the Probe Status Request message as relayed by a Repeater Node, not directly from a Probe, so you'll need to adapt it to decode the Probe Status service directly.* I didn't have a Python example handy showing how to decode the USDA Safe data. 

```python
        # Decode the payload
        serial_and_logs = list(bitstruct.unpack("u32u32u32", bytes(self.payload)))
        self.probe_serial_num = int.from_bytes(serial_and_logs[0].to_bytes(4, byteorder='little'), byteorder='big', signed=False)
        self.log_range_low = int.from_bytes(serial_and_logs[1].to_bytes(4, byteorder='little'), byteorder='big', signed=False)
        self.log_range_high = int.from_bytes(serial_and_logs[2].to_bytes(4, byteorder='little'), byteorder='big', signed=False)

        # Temperatures
        swapped = byteswap([13], bytes(self.payload), 12)
        temperature_data = list(bitstruct.unpack("u13u13u13u13u13u13u13u13", bytes(swapped)))
        # Little-endian temperature fields are in reverse order.
        self.temperatures = (to_temp(temperature_data[7]), to_temp(temperature_data[6]),
            to_temp(temperature_data[5]), to_temp(temperature_data[4]), to_temp(temperature_data[3]),
            to_temp(temperature_data[2]), to_temp(temperature_data[1]), to_temp(temperature_data[0]))

        status_data = list(bitstruct.unpack_from("u8u8", bytes(self.payload), 25*8))

        # Mode/Color/ID
        mode_id_byte = status_data[0]
        self.mode = mode_id_byte & 0x3
        self.color = (mode_id_byte & 0x1C) >> 2
        self.id = (mode_id_byte & 0xE0) >> 5

        # Battery and virtual sensors
        status_byte = status_data[1]
        self.battery_status = (status_byte & 0x1)
        self.core_sensor = f"T{((status_byte & 0xE) >> 1) + 1}"
        self.surface_sensor = f"T{((status_byte & 0x30) >> 4) + 4}"
        self.ambient_sensor = f"T{((status_byte & 0xC0) >> 6) + 5}"

        # Prediction info
        prediction_swapped = byteswap([7], bytes(self.payload), 27)
        # Note - these fields are in reverse order
        prediction_data = list(bitstruct.unpack_from("u11u17u10u10u2u2u4", bytes(prediction_swapped)))
        self.prediction_state = prediction_data[6]
        self.prediction_mode = prediction_data[5]
        self.prediction_type = prediction_data[4]
        self.prediction_setpoint = prediction_data[3] * 0.1
        self.heat_start_temperature = prediction_data[2]
        self.prediction_value_sec = prediction_data[1]
        self.estimated_core_temp = prediction_data[0]
        
        # Food Safe Data 
        def decode_food_safe_data_float(value):
            return float(value * 0.05)
        food_safe_swapped = byteswap([10], bytes(self.payload), 34)
        # Note - these fields are in reverse order
        food_safe_data = list(bitstruct.unpack_from("u4u8u13u13u13u13u3u10u3", bytes(food_safe_swapped)))
        self.food_safe_mode = food_safe_data[8]
        self.food_safe_product = food_safe_data[7]
        self.food_safe_serving = food_safe_data[6]
        self.food_safe_threshold_temperature = decode_food_safe_data_float(food_safe_data[5])
        self.food_safe_z_value = decode_food_safe_data_float(food_safe_data[4])
        self.food_safe_reference_temperature = decode_food_safe_data_float(food_safe_data[3])
        self.food_safe_d_value_at_rt = decode_food_safe_data_float(food_safe_data[2])
        self.food_safe_target_log_reduction = food_safe_data[1] * 0.1
        # Note - the first 4 bit field is padding

        # Food Safe Status
        food_safe_status_swapped = byteswap([8], bytes(self.payload), 44)
        food_safe_status = list(bitstruct.unpack_from("u5u32u16u8u3", bytes(food_safe_status_swapped)))
        # Note - these fields are in reverse order
        self.food_safe_state = food_safe_status[4]
        self.food_safe_log_reduction = food_safe_status[3] * 0.1
        self.food_safe_sec_above_threshold = food_safe_status[2]
        self.food_safe_log_sequence_number = food_safe_status[1]
        # Note - the first 5 bit field is padding

        # Network info
        network_data = list(bitstruct.unpack_from("u8", bytes(self.payload), 51*8))
        network_info_byte = network_data[0]
        self.hop_count = (network_info_byte & 0xC0) >> 6
```

**Comment by jmaha** [comment]
I should mention too, this type of inquiry is great to post on our [Reddit](https://www.reddit.com/r/combustion_inc/), as a number of folks in the community have written libraries in several languages for interfacing with the Combustion products and are a great resource--we try to keep technical support discussions there where it's more discoverable.

**Comment by legrego** [comment]
@jmaha thank you for taking the time to provide such a detailed response. Your explanation and code snippet clarifies quite a bit for me.

>  At some point I hope to clean up and release our Python-based libraries for interfacing with probes and repeater devices, which would provide helpful example code for decoding these fields.

This is precisely what I'm working on, but primarily in service of https://github.com/legrego/homeassistant-combustion. I have an extremely crude implementation within that repository, but I've since decided to port your Swift SDK to python so that it can act as a standalone package, rather than coupled to my Home Assistant needs. If you already have a python package internally, then perhaps I'll wait for yours to be released.

**Comment by jmaha** [comment]
I took a look through your repo—nice work! It looks like your library is built using Bleak, right? Ours is as well. Our Python library is focused on directly testing / exercising devices for development and manufacturing test. Your home assistant library adds a lot of value, and I think our code, particularly the message encoding/decoding, will save you some time. Let me chat with Chris and figure out a plan to make it public.  On Jan 10, 2024, at 4:13 AM, Larry Gregory ***@***.***> wrote:﻿
@jmaha thank you for taking the time to provide such a detailed response. Your explanation and code snippet clarifies quite a bit for me.

At some point I hope to clean up and release our Python-based libraries for interfacing with probes and repeater devices, which would provide helpful example code for decoding these fields.

This is precisely what I'm working on, but primarily in service of https://github.com/legrego/homeassistant-combustion. I have an extremely crude implementation within that repository, but I've since decided to port your Swift SDK to python so that it can act as a standalone package, rather than coupled to my Home Assistant needs. If you already have a python package internally, then perhaps I'll wait for yours to be released.

**Comment by legrego** [comment]
Yes, I'm using Bleak for BT comms -- great to hear that yours is built on that as well. Looking forward to hearing back about your plans. If your timeline isn't in the near-term, then I'll continue with my library as a stopgap.

I should have asked y'all if there was a python implementation before writing my own, but if nothing else this was a good excuse to learn more about BT comms and byte sequences :slightly

**Comment by legrego** [comment]
I've published what I have so far, just to get it off of my machine: https://github.com/legrego/combustion_ble
