### ISSUE TITLE
Communicating with probe using nRF Connect Android app

### ISSUE THREAD

**Issue by MarcelloTheArcane** [combustion-inc/combustion-documentation#25]
Hello,

I'm thinking about using an ESP32 as a MeatNet device, and am trying to work through the spec using the nRF Connect app to make sure I understand how to connect & communicate with the devices. 

I've connected to a probe and am sending the following to the UART service RX (`6e400002-b5a3-f393-e0a9-e50e24dcca9e`):

```
CA FE 48 5C 03 00
```

I used [this site](https://crccalc.com/) to generate the CRC-16/CCITT-FALSE for bytes `03 00`, and I'm trying to send the session ID request, just as a test.

However, I can't seem to see the response.  What am I missing?

![Screenshot_20240317_162320_nRF Connect](https://github.com/combustion-inc/combustion-documentation/assets/21159570/5b5a91ab-a5c0-4aed-a857-8df019829a38)

![Screenshot_20240317_163725_nRF Connect](https://github.com/combustion-inc/combustion-documentation/assets/21159570/099620d8-12fe-4af6-9a1a-a5098317d7be)

**Comment by jmaha** [comment]
Hi, sorry for the delayed response. We're a small team and don't have the resources to provide tech support for our open source libraries. Our [Reddit](https://www.reddit.com/r/combustion_inc/) is a good resource as community members have posted a number of examples for doing this kind of custom integration.
