### ISSUE TITLE
Probe Status Service - Food Safe Status Data Size Clarification

### ISSUE THREAD

**Issue by flynace** [combustion-inc/combustion-documentation#27]
Hi,
The [Probe Status Service UUID](https://github.com/combustion-inc/combustion-documentation/blob/main/probe_ble_specification.rst#probe-status-service) summary lists 44 bytes with the Food Safe Status being uint8_t formatted 4 bytes of data.

However, the [Food Safe Status](https://github.com/combustion-inc/combustion-documentation/blob/main/probe_ble_specification.rst#food-safe-status) description states it's a packed 8-byte field detailing 59 bits of data as follows:
- Bits 1-3 = Food Safe State (3 bit enumeration)
- Bits 4-11 = Log Reduction (8 bit encoded decimal)
- Bits 12-27 = Seconds above threshold (16 bit unsigned integer)
- Bits 28-59 = Food Safe log sequence number (32 bit unsigned integer)

Can you confirm Food Safe Status payload is 4 or 8 bytes and the Probe Status Service is 44 or 48 bytes?
And the last 5 bits of the Food Safe Status are just Reserved?

Thanks

**Comment by jmaha** [comment]
Hi, sorry for the delayed response. Good catch, the Food Safe Status payload is 8 bytes, so the Probe Status Service is 48 bytes. I'll correct this.

Heads up, we're adding an additional byte to the Probe Status service that will contain a bitmask about which sensors are overheating, which will increase the size of the service to 49 bytes.

**Comment by jmaha** [comment]
Corrected typo in PR #29 .
